#import "/local-lib/template-thesis.typ": *
#import "/metadata.typ": *
#pagebreak()
= Validation <sec:validation>

In this chapter I document how I evaluated the Vakansio pipeline and what the evaluation found. The chapter has two equally important aims. The first is to describe a solid evaluation approach — split into independent layers, each measured with the right technique for its data type — that another engineer could rerun and extend. The second is to report the findings honestly. The primary result on ranking quality is inconclusive at the conventional significance level on the gold set available within the project's scope. The decomposition follows the Holistic Evaluation of Language Models framework #cite(<liangHolisticEvaluation2023>) and uses an Anthropic Claude judge where no reference answer exists to compare against #cite(<zhengJudgingLLMasaJudge2023>).

== Evaluation philosophy and methodology pivot <sec:validation:pivot>

In this section I explain how my evaluation strategy reached its current shape. My first design used one end-to-end metric — score MAE — as the main evidence for the claim that the Composite Judge improves match quality over a linear weighted sum of the sub-scores. Two independent audits found three structural problems with that metric, so I revised the design before collecting the final results. The revised design keeps the score-error metric as a calibration diagnostic and uses top-k ranking quality against independent-vendor LLM ratings as the new primary endpoint.

*Why I demoted the original score-error metric.* The score-error harness compares the pipeline's output to a deterministic ideal computed from gold inputs. The audits found three problems with this comparison:

- *Cap asymmetry.* The pipeline applies safety caps and an anti-flag penalty (@sec:design:scoring); the ideal does not. Any pipeline that ships caps is mechanically penalised on this metric.
- *Selection circularity.* The gold pair set was split on three signals — title overlap, seniority match, and skill overlap — that are the very inputs the Linear pipeline uses. The test set is engineered to favour the Linear baseline.
- *Composite Judge over-penalisation.* The Judge prompt has rule-precedence clauses that allow it to override its bounded-adjustment band on under-qualification, language gap, or family mismatch, and the post-judge clamp does not enforce the bound. This is a real calibration issue, but it is more useful as a per-axis diagnostic than as the headline result.

*The revised primary endpoint.* I adopted top-ten NDCG against independent-vendor relevance ratings as the new primary evidence. The rater is from Anthropic's Claude family; the system under evaluation runs on Google's Gemini. Using a different vendor avoids the circular reasoning the original harness had. A full multi-vendor ensemble — adding judges from a second non-Anthropic family — would strengthen the protocol further and is recorded as future work in @sec:validation:threats. My protocol follows Zheng et al. #cite(<zhengJudgingLLMasaJudge2023>): anchor-only ordinal ratings, randomised candidate order, mandatory per-rating rationale, and stratified batches across verdict buckets. The same protocol underpins the rubric-based evaluation of the bilingual reason text in @sec:validation:reason.

*What this chapter reports.* I organise the remainder of the chapter around the five evaluation layers that emerged from this design. @sec:validation:architecture describes the layered decomposition. @sec:validation:norm summarises the two structured-output normalisation layers that I froze before the methodology pivot. @sec:validation:score reports the score-error metric as a calibration diagnostic, including the per-axis bias decomposition. @sec:validation:reason reports the reason-text-quality layer, including the complete prompt iteration cycle the eval pipeline guided through four versions. @sec:validation:ranking reports the primary endpoint on top-ten ranking quality, including the per-curriculum-vitae variance behind the headline confidence interval. @sec:validation:threats names the limitations of the evaluation and the specific extensions that would resolve each. A worked example tracing a single (curriculum vitae, vacancy) pair through every layer is in @sec:appendix.

== Layered evaluation architecture <sec:validation:architecture>

The pipeline produces four things per (CV, vacancy) pair: a structured CV summary, a structured vacancy analysis, a numeric score, and a bilingual reason text. My main choice: evaluate each one with a method that fits its data type, instead of squashing everything into one end-to-end number. A single metric blurs failures across stages and makes fixes harder. My decomposition follows the Holistic Evaluation of Language Models framework #cite(<liangHolisticEvaluation2023>). The five layers I use are the road map for the rest of the chapter:

- *Layer 1 — CV normalisation.* Structured JSON, graded against my own reference normalisations. Headline: per-field F1 = 0.896 on 25 CVs. Frozen after nine prompt versions.
- *Layer 2 — Vacancy normalisation.* Structured JSON, graded against my own reference normalisations. Headline: per-field overall = 0.810 on 355 of 357 vacancies. Frozen after twelve prompt versions.
- *Layer 3 — Score.* Numeric scalar in $[0, 1]$ compared to a computed ideal from gold inputs. Headline: Linear MAE = 0.101, Composite MAE = 0.187 on 392 pairs. Kept as a calibration diagnostic (see @sec:validation:score).
- *Layer 4 — Reason text.* Bilingual natural language, judged by Claude Opus 4.7 on a six-dimension rubric. Headline: overall rubric mean = 8.35 / 10 on 391 pairs. Prompt v6 wins $+0.30$ over the v4 baseline.
- *Layer 5 — Ranking.* Top-ten ordered list, judged by Claude Sonnet 4.6 on a single match-quality score. Headline: $Delta$ NDCG\@10 = $-0.047$, 95% CI $[-0.168, +0.065]$ on 14 CVs. Inconclusive at $alpha = 0.05$.

Each layer owns its own failures. A misclassified vacancy is a Layer 2 problem regardless of the score. A weak reason on a correctly scored pair is a Layer 4 problem. A stable score but a worse top-ten ordering is a Layer 5 problem. Each layer also uses the method the literature treats as standard for that data type: hand-annotated references with field-level scoring for the two structured layers, a computed ideal for the numeric layer, LLM-as-Judge on a rubric for the natural-language layer #cite(<zhengJudgingLLMasaJudge2023>), and ordering-quality metrics (NDCG, Spearman, Kendall) against per-pair relevance ratings for the ranking layer #cite(<jarvelinCumulatedGainBased2002>). The same separation Clean Architecture imposes on the production code (@sec:design:clean-arch) organises the evaluation: the Domain types the scoring service consumes are exactly the inputs my eval tool feeds to each layer. The eval tool, a separate .NET project under #raw("EvalTool/"), runs offline against snapshots of the gold data and shares the production interfaces, so it tests the same code paths that ship to users.

== Layers 1 and 2 — frozen normalisation baselines <sec:validation:norm>

In this section I report the two structured-output normalisation layers, both of which I closed before the methodology pivot in @sec:validation:pivot and against whose frozen state the later layers compose. Both layers follow the same shape: a gold set of author-curated reference normalisations, a battery of per-field graders applied to the pipeline output, and an append-only history journal that records every iteration of the prompt or post-processor.

*Layer 1 — curriculum-vitae normalisation.* The gold set comprises twenty-five curricula vitae, which I normalised into the same JSON shape that the production pipeline persists as #raw("UserProfile.CvSummary"). Nineteen field-level scored metrics are computed by the graders declared in #raw("EvalTool/Grading/EvaluationEngine.cs"): F1 for skill list comparisons (#raw("technical_skills"), #raw("domain_skills"), #raw("unverified_skills")), Jaccard overlap for target-role lists, exact-match for categorical fields (seniority, work format), and an ordinal-distance grader on the Common European Framework of Reference ladder (A1–C2) for English level. The headline number is the macro-averaged score across these metrics. The current production CV-normalisation service reaches an overall score of 0.896 on this gold set after nine prompt versions; I preserve the iteration history in #raw("eval_history/runs.csv"). I consider the layer frozen because subsequent runs change the headline number by less than the per-iteration noise observed across the last three iterations.

*Layer 2 — vacancy normalisation.* The gold set comprises three hundred and fifty-seven vacancies I sampled across the seven source adapters and stratified to cover four heuristic strata (Strong, Partial, Weak, Mismatch) that align with the Composite Judge verdict bucket names. I normalised each vacancy into the same JSON shape that the production pipeline persists as #raw("JobVacancy.VacancyAnalysisJson"), and seventeen field-level scored metrics are computed by the graders declared in #raw("EvalTool/Grading/VacancyEvaluationEngine.cs"), adapted to the vacancy schema (must-have skill lists, nice-to-have skill lists, domain, seniority, work format, language requirement). The current production vacancy-normalisation service reaches an overall field-weighted score of 0.810 across three hundred and fifty-five of the three hundred and fifty-seven gold vacancies (two were excluded by the loader because of malformed source records) after twelve prompt versions; the iteration history is preserved in #raw("eval_history/vacancy/runs.csv"). I consider the layer frozen on the same noise-threshold criterion as Layer 1.

*What the frozen baselines fix, and what they do not measure.* Because Layers 1 and 2 are frozen, all the later layers run against a known, reproducible upstream. I report Layer 3 and Layer 5 results both against the production normalisation services and (in parallel) against the gold normalisations directly, which gives an upper bound on what the pipeline could reach with perfect upstream. Layer 4 is reported only against the production path because reason text is generated after scoring. Two caveats. First, per-field F1 measures how well the pipeline matches my own gold annotation — not how well the annotation matches reality. Both gold sets were curated by a single annotator (me), and I did not collect an inter-annotator coefficient. Second, the fields with lowest F1 — the skill lists, between roughly 0.47 and 0.62 — are the same fields the scoring formula leans on hardest. I come back to both points in @sec:validation:threats.

== Layer 3 — score as a calibration diagnostic <sec:validation:score>

In this section I report the score-error layer and explain why I keep it as a calibration diagnostic rather than as the primary evidence for the thesis claim. The layer measures how closely the pipeline's end-to-end composite score tracks a deterministic ideal computed on gold inputs. The harness was my original primary endpoint; the methodology pivot in @sec:validation:pivot moved it to a diagnostic role after two independent audits found three structural issues that make the metric a poor fit for the question the thesis actually asks.

*The harness.* For every (curriculum vitae, vacancy) pair in a fixed three-hundred-and-ninety-two-pair test set, the harness loads the gold CV summary and the gold vacancy analysis, runs the seven sub-score calculators on those gold inputs, and clamps the weighted sum to $[0, 1]$. The resulting #raw("ideal_score") is the raw weighted sum with no anti-flag penalty, no missing-must-have soft penalty, no language-gap cap, and no family-mismatch cap. The harness then reads the pipeline's end-to-end output for the same pair and reports the absolute difference. The harness is implemented in #raw("EvalTool/Grading/ScoringEvaluationEngine.cs") and is run through the orchestrator entry point #raw("ScoringEvalOrchestrator.cs").

*First-look numbers.* On the 392-pair test set, the Linear pipeline (weighted sum of the seven sub-scores, no Composite Judge) reaches 0.899 overall — MAE 0.101, verdict-bucket match 67.3 per cent. The Composite pipeline (Judge invoked on every pair) reaches 0.813 — MAE 0.187, verdict-bucket match 31.9 per cent. The naive reading says the Composite Judge is worse than the Linear baseline. The two audits show why that reading is misleading.

*Three audit findings (in summary).* I summarise the three structural issues here; the full audit decomposition is in #raw("Capstone Project/EVAL_VALIDITY_APPENDIX.md").

- *Cap asymmetry.* The pipeline applies the safety caps and anti-flag penalty from @sec:design:scoring; the ideal does not. A per-pair decomposition reveals that approximately fourteen per cent of pairs carry an active anti-flag and drift by an average of $-0.379$ against the ideal, while the remaining eighty-six per cent without an anti-flag drift by an average of $-0.056$. Together these account for almost all of the Linear pipeline's headline error: $0.14 times 0.379 + 0.86 times 0.056 = 0.101$, matching the Linear MAE exactly. So the metric measures the caps, not pipeline quality.
- *Selection circularity.* I stratified the 392-pair test set on title overlap, seniority match, and skill overlap — the same primitives the Linear pipeline's #raw("RoleIntentMatchCalculator") and #raw("SkillMatchCalculator") consume. The Linear pipeline is graded on its home turf. The audit estimates this asymmetry inflates the Linear advantage by 0.02–0.04 MAE points (40–50 per cent of the visible gap).
- *Composite Judge over-penalisation.* The Judge prompt's rule zero requires output within $plus.minus 0.05$ of the input linear score, but rules three (under-qualification), four (language cap), and five (different-family cap) explicitly override rule zero when triggered, and the post-Judge clamp in #raw("GeminiCompositeJudgeService.cs") enforces $[0, 1]$ but not the $plus.minus 0.05$ band. The five largest Linear-to-Composite divergences are $-0.39, -0.38, -0.26, -0.23, -0.21$, all on pairs where one of the three override rules fired. The fix is straightforward: enforce a hard $abs(s_"judge" - s_"linear") <= 0.10$ clamp at the boundary.

*What remains after the artefacts are subtracted.* Of the visible 0.086 gap between the Linear and Composite headlines, the audits attribute roughly 0.04 to eval-engine artefacts (cap asymmetry plus selection circularity) and roughly 0.05 to the Composite over-penalisation. Subtract both and the Composite Judge would still underperform on the score-tracking metric, but the gap would be about half what the headline suggests. I confirm this empirically in @sec:validation:ranking: running the saved Composite scores through a post-hoc $plus.minus 0.10$ clamp collapses the largest negative outlier from about $-0.54$ to essentially zero.

*Why this metric answers the wrong question.* The deeper point: score-tracking is the wrong primary endpoint. The thesis claim is about ranking quality — whether the Composite top-ten is better-ordered against human-judged relevance than the Linear top-ten. A pipeline can have a higher MAE against the linear ideal while still ordering its top ten better. I replaced the primary endpoint; the new endpoint is in @sec:validation:ranking. The score-tracking harness stays because the per-sub-score bias breakdown it produces — for example, $+0.028$ on #raw("DomainAlignment") and $+0.045$ on #raw("RoleIntentMatch") — is useful when I rebalance a sub-score calculator.

== Layer 4 — reason-text quality and the prompt iteration cycle <sec:validation:reason>

In this section I report the reason-text-quality layer, which evaluates the bilingual English and Ukrainian explanations the pipeline generates for the top-thirty candidate vacancies in every result. The data type here is short natural-language text, so the field-grader method used in Layers 1 and 2 does not work. My methodology is large-language-model judging on an independent Anthropic Claude family on a structured rubric, following the protocol of Zheng et al. #cite(<zhengJudgingLLMasaJudge2023>) and the domain-specific rubric design of Hu et al. for hiring explanations #cite(<huAiHiringLLMs2025>).

*The judge.* My judge model is Claude Opus 4.7 from Anthropic. The choice of an Anthropic judge avoids the within-system bias that a same-family judge would carry: the model whose outputs are being rated is Google's Gemini 2.5 Flash, so the judge and the system under test come from different vendor families. Opus is the strongest model in the Anthropic family at the time of the evaluation; Zheng et al. recommend using the strongest tier on the judge side in an asymmetric setup. Using a single judge family is a deliberate scope choice, not the final word on method: I record a full multi-vendor ensemble as the principal limitation in @sec:validation:threats.

*The rubric.* Each (candidate, vacancy) reason text is rated on six dimensions. Four are ordinal on the six-point anchor set $\{0, 2, 4, 6, 8, 10\}$: #raw("factual_accuracy") (do the strengths, gaps, and context claims correspond to the actual CV and vacancy content?), #raw("completeness") (are the top factual signals surfaced?), #raw("specificity") (is the phrasing pair-unique rather than generic boilerplate?), and #raw("relevance_for_user") (is the explanation actionable for an apply-or-skip decision?). Two are binary: #raw("verdict_match") (does the verdict word agree with the score bucket?) and #raw("uk_term_preservation") (are technical brand-and-tool tokens preserved in Latin script in the Ukrainian half?). I record the rubric, the anchor descriptions, and worked examples in #raw("docs/research/reason_eval_rubric.md").

*Bias mitigation in the judging protocol.* I apply five mitigations per Zheng et al. I anonymise candidate identifiers at random (candidate A versus candidate B, with a random mapping back to the actual prompt version being tested). I instruct the judge not to compare candidates against one another within a pair, only against the rubric. The ordinal dimensions use anchor-only scoring with no intermediate values. Pairs are organised into batches of twenty-eight stratified proportionally across the four verdict buckets. The judge emits a per-rating rationale alongside each numeric score, for human inspection and downstream auditability.

*Does the judge agree with itself? — pilot check.* Before running the main ratings, I called the Claude Opus 4.7 judge twice on the same ten pilot pairs, with randomised order and non-zero temperature, and computed Krippendorff's $alpha$ across the rubric. This number says how often the judge agrees with itself across two runs — it is *not* a check that two different vendors agree with each other. My threshold was $alpha gt.eq 0.6$ for ordinal dimensions and $alpha gt.eq 0.7$ for binary ones, slightly below the standard Krippendorff (2004) threshold of 0.667. I used the lower bar because this check is meant to catch a wildly unstable judge, not to formally prove rater reliability. Mean ordinal $alpha$ on the pilot was 0.695, with binary raw agreement between 93 and 97 per cent. The lowest per-dimension $alpha$ — #raw("factual_accuracy") at $alpha = 0.603$ — was 0.003 below the threshold; I report it openly. A real cross-vendor inter-rater check remains the main limitation (@sec:validation:threats).

*Author spot-check of the gold ratings.* I did not treat the judge ratings as a black box. I picked a stratified sample of pairs across the four verdict buckets and read each one end-to-end — the CV, the vacancy, the judge's score on every dimension, and the rationale. The point was a sanity check, not a re-annotation. The judge's ratings still served as the gold values in the statistical inference. On the spot-checked pairs I saw no obvious bias pattern, but I want to be clear: I am the author of the project under evaluation, so I am not a disinterested rater, and I report the spot-check for transparency, not as an independent gold standard.

*Statistical inference protocol.* For each prompt-version comparison, my headline number is the paired difference of the per-pair overall mean across all six dimensions. Confidence intervals come from paired bootstrap with ten thousand resamples. Per-dimension deltas are reported separately as exploratory signals.

*The prompt iteration cycle.* I demonstrate a complete detect-fix-validate-iterate loop through four prompt versions, each developed in response to a regression that the previous iteration surfaced. @tab:validation:prompt-iter summarises the comparison endpoints.

#figure(
  table(
    columns: 5,
    stroke: none,
    align: (left, right, left, left, left),
    inset: 5pt,
    table.header(
      [*Comparison*],
      [*$Delta$ overall*],
      [*95% CI*],
      [*Significant at $alpha = 0.05$*],
      [*Headline signal*],
    ),
    [v4 vs v2], [$+0.55$], [$[+0.42, +0.68]$], [Yes], [Context enrichment works, factual regression detected],
    [v5 vs v4], [$-0.03$], [$[-0.14, +0.08]$], [No], [Targeted fix introduces a recall trade-off],
    [v6 vs v4], [$+0.30$], [$[+0.19, +0.40]$], [Yes], [Templates resolve trade-off across all four ordinal dimensions],
  ),
  caption: [Paired-bootstrap overall reason-quality deltas across the three head-to-head studies. Each study uses approximately 391 pairs, anonymised, with the protocol described in this section.],
) <tab:validation:prompt-iter>

The per-version story in one sentence each: *v4* added context-lead phrasing and a #raw("ReasonContext") record from #raw("ScoringServiceV2.BuildReasonContext()") with a #raw("ReasonValidator") safety net, gaining $+0.55$ overall over v2 but regressing #raw("factual_accuracy") by $-0.43$ when the language model inferred labels from its own judgement; *v5* rewrote the context-lead rule to forbid inference and require strict #raw("ReasonContext") referencing, recovering #raw("factual_accuracy") by $+0.71$ but regressing #raw("completeness") by $-0.62$ and #raw("relevance_for_user") by $-0.37$ as the model became too cautious; *v6* replaced free-form context generation with four constrained templates (Role-Family Mismatch, Cross-Domain, Overqualification, Underqualification) that interpolate literal #raw("ReasonContext") values into fixed sentence shapes, producing significant gains on all four ordinal dimensions (#raw("factual_accuracy") $+0.50$, #raw("completeness") $+0.23$, #raw("specificity") $+0.77$, #raw("relevance_for_user") $+0.31$, overall $+0.30$) and is the production version. The iteration cycle itself is a contribution: each detection was a confidence-interval calculation, not a guess, and each fix was a single component change with the rest of the pipeline held still.

== Layer 5 — top-ten ranking quality (the primary endpoint) <sec:validation:ranking>

In this section I report the primary endpoint of the thesis: top-ten Normalised Discounted Cumulative Gain (NDCG\@10) #cite(<jarvelinCumulatedGainBased2002>) of the Composite pipeline against the Linear baseline, measured on a per-(CV, candidate-set) basis with paired-bootstrap confidence intervals. The endpoint is what the original thesis claim is actually about — whether the Composite pipeline produces a better-ordered top-ten list than the Linear pipeline — and I adopted it after the methodology pivot in @sec:validation:pivot.

*The judge.* For this layer my judge is Claude Sonnet 4.6 from Anthropic, distinct from the Claude Opus 4.7 judge in @sec:validation:reason. The choice of the more cost-effective tier reflects the task: each per-pair rating is a single ordinal value on the anchor set $\{0, 2, 4, 6, 8, 10\}$ rather than the six-dimension rubric Layer 4 requires, and I need the ratings at scale (391 pairs across 14 CVs). The cross-vendor configuration is preserved — an Anthropic judge rates the output of the Gemini-backed Vakansio pipeline — and the same anchor-only ordinal protocol with mandatory per-rating rationale and randomised candidate order is applied. The single-vendor judge limitation is named explicitly in @sec:validation:threats.

*The rated quantity.* The judge rates each (CV, vacancy) pair on a single dimension named #raw("match_quality"). Anchor descriptions span the range from "no signal of fit between the candidate and the vacancy" at zero to "the candidate is an exceptional match for the role as described" at ten. Pairs are presented to the judge with the full CV summary and vacancy analysis but without either pipeline's score; the rating is therefore a relevance signal independent of either system under test.

*Author spot-check of the match-quality ratings.* I subjected the match-quality gold set to the same plausibility audit described in @sec:validation:reason — a stratified sample across verdict buckets, read end-to-end against the supporting evidence — and recorded no rater-flagged bias pattern. The same absence-of-evidence limitation and the same single-rater interest in the outcome apply.

*The endpoint and the test.* For each of the 14 CVs, I independently rank the candidate vacancy set (approximately 28 vacancies per CV, stratified across verdict buckets) by the Composite pipeline and by the Linear pipeline, and score the top ten of each against the judge's match-quality ratings using the standard NDCG\@10 definition with $log_2$ discounting. The per-CV primary statistic is the difference between the Composite and Linear NDCG\@10. The aggregate statistic is the mean of the per-CV differences, with a 95 per cent paired-bootstrap confidence interval over the 14 CVs (10,000 resamples).

*The headline result.* The mean of the per-CV differences is $Delta "NDCG"@10 = -0.047$, with a 95 per cent paired-bootstrap confidence interval of $[-0.168, +0.065]$. The interval crosses zero. Cohen's $d$ on the per-CV differences is $-0.199$ — a small directional effect favouring the Linear pipeline. The per-CV outcome is five Composite wins, nine Linear wins, no ties. My honest reading: the thesis claim that the Composite Judge improves ranking quality is neither supported nor refuted on this gold set. The data warrant "directionally non-significant" — not "wins", not "loses".

*Both pipelines rank well on the full ordering.* When I look at the full ordering (not just the top ten), both pipelines correlate strongly with the judge's relevance ratings. Per-CV Spearman correlation is $rho = +0.690$ for Composite and $rho = +0.691$ for Linear; Kendall's $tau$ is $+0.481$ and $+0.503$. Both are far above what a random ranker would produce. The underlying scoring methodology works regardless of whether the Composite Judge stage is enabled, and the two pipelines are statistically indistinguishable on the full ordering too.

*The headline hides a big spread between CVs.* The Composite pipeline wins on some CVs and loses on others. It wins where the Judge's qualitative call changes the ordering for the better — a senior QA automation CV ($Delta = +0.331$), a frontend-engineer CV with React vs. Angular candidates ($Delta = +0.158$), and my own career-switching product-manager CV ($Delta = +0.199$). It loses where the deterministic skill match is already strong and the Judge adds noise — a broad full-stack CV where the Judge over-penalises depth specialisation ($Delta = -0.643$), an engineering-manager CV ($Delta = -0.263$), and a senior PM CV ($Delta = -0.172$). The single broad-full-stack CV alone drives most of the negative aggregate. Remove it and the mean delta drops to about $-0.001$ — essentially a tie. I keep the outlier in the headline because cutting inconvenient data is itself risky, but I flag it openly here so the reader can judge it.

*Sensitivity check under the proposed calibration clamp.* The fix from @sec:validation:score is a hard $plus.minus 0.10$ clamp at the boundary of #raw("GeminiCompositeJudgeService"). The clamp is a simple post-processing filter on the Judge's output. The Composite and Linear scores are already saved per pair, so I apply the clamp arithmetically to those saved scores. There is no need to re-run the Gemini Judge calls: the clamp does not change what the model decides, only the value the boundary returns. I apply it per pair as $s'_"composite" = max(s_"linear" - 0.10, min(s_"linear" + 0.10, s_"composite"))$ and recompute NDCG\@10 against the unchanged Sonnet ratings. The sensitivity analysis reproduces the published $Delta = -0.047$ within rounding as $Delta = -0.040$. Under the clamp the mean moves to $Delta = +0.018$, with a 95 per cent CI of $[-0.054, +0.091]$ that still crosses zero. The sign flips from negative to positive, but the verdict — "directionally non-significant" — does not change. The largest outlier, the broad-full-stack CV #raw("17_realformat_swe_fullstack"), drops from about $-0.54$ to $approx 0$ under the clamp, confirming the audit's attribution to the rule-precedence over-penalisation. The per-CV outcome shifts from 5–9 to 7–7. I record deploying the fix as future work in @sec:conclusion because production deployment needs a fresh pipeline run; the point reported here is that the methodology's verdict holds whether the fix ships or not.

*What this layer does and does not claim.* The layer does not claim that the Composite Judge improves ranking quality. It does not claim the opposite either. The interval crosses zero. What the layer does claim is that the methodology is sound: independent-vendor LLM judging on an anchor-only relevance scale, NDCG\@10 with paired-bootstrap intervals, per-CV variance reported openly, and the largest negative case attributed to a fixable calibration defect. The current answer is honestly inconclusive on this gold set. The conditions under which the answer would change are in @sec:validation:threats. A full end-to-end worked example tracing a single (CV, vacancy) pair through all five layers is in @sec:appendix.

== Layer 6 — held-out validation against a fresh-pair, fresh-vacancy gold set <sec:validation:heldout>

In this section I report the strongest evidence the thesis has on the recruiter-side scoring pipeline: an evaluation against a held-out gold set of 398 (curriculum vitae, vacancy) pairs that the production prompt never saw during iteration. The gold set was built in two stages described in @sec:validation:heldout:methodology — an initial pair-level held-out (131 pairs drawn from the development vacancy pool) and a fresh-vacancy extension that scraped and normalised 300 new vacancies after the production prompt was frozen, then paired them with the 25 curriculum-vitae pool. By the final stage, $126 / 398 = 31.7%$ of all pairs use vacancies the production prompt has provably never seen, in addition to the 11 curricula vitae in the safety subset that have provably never been used during prompt iteration. The held-out layer closes the *selection-circularity*, *single-annotator*, and *vacancy-pool partial leakage* threats named in @sec:validation:threats, and provides the first controlled ablation of the production #raw("ScoringCapService") against the bare language-model composite.

The headline result on the held-out set is that the production scoring system achieves Spearman $rho = 0.648$ ($95%$ CI $[0.580, 0.712]$) and Quadratic Weighted Kappa $kappa_Q = 0.638$ against the Opus gold, with mean absolute error $1.638$ on the native ordinal 0–10 scale ($95%$ CI $[1.533, 1.745]$), and Normalised Discounted Cumulative Gain $"NDCG"@5 = 0.82$ averaged across the 25 curricula vitae used as queries. On the *midrange filter* — pairs where the gold rating is non-trivial ($\{4, 6, 8, 10\}$, $n = 110$) — the Spearman correlation rises to $rho = 0.738$ and the mean absolute error falls to $1.13$.

=== Methodology <sec:validation:heldout:methodology>

*Three-subset held-out design.* A held-out gold set has a different risk profile from a development set: every pair must be one the prompt was never tuned against. The design I used has three subsets each addressing a distinct failure mode. The *safety subset* ($n = 189$) consists of eleven curricula vitae from professional families that never appeared in development (junior product designer, junior DevOps engineer, HR recruiter, junior nurse, senior cardiologist, corporate lawyer, senior English teacher, senior accountant, growth marketer, academic professor of humanities, mid security engineer), each paired with approximately seventeen vacancies sampled from across the full 657-vacancy pool, biased toward technology roles to test catastrophic-mismatch detection. The *coverage and strong-fit subset* ($n = 209$) consists of the 14 curricula vitae used in development plus the same 11 fresh curricula vitae, paired with vacancies stratified across role families (same family, adjacent family, cross-family, same-seniority-same-family strong fit); each pair is novel and a large fraction use the fresh-vacancy extension described below. The *midrange filter* ($n = 110$) is a cross-cutting filter over the above two subsets restricted to pairs where the gold rating falls in $\{4, 6, 8, 10\}$ — the regime where the recruiter's decision between candidates actually happens.

*Two-stage dataset construction.* The held-out gold was built in two stages, each addressing a distinct subset of the threats named in @sec:validation:threats. Stage 1 produced an intra-pool held-out (initially 131, then 272 pairs after a first expansion) drawn from the existing 357-vacancy production pool; the Stage-1 gold addresses the *selection-circularity* threat — the prompt did not see these specific pairings during iteration — but it does not address *vacancy-pool partial leakage* because the vacancy text itself was seen during normalisation prompt iteration. Stage 2 added a fresh-vacancy extension of 126 pairs: 1,543 new vacancies were scraped from #raw("work.ua") and #raw("djinni.co") using non-tech queries (legal, healthcare, HR, marketing, finance, sales, design, education, security), the first 300 normalised via the same #raw("IVacancyExtractionService") the production API uses, and the 300 fresh vacancies paired with the 25 curricula vitae stratified across professional families. The production prompt provably did not see the vacancy text for these pairs during iteration. This stage retires the *vacancy-pool partial leakage* threat for these 126 pairs and shifts the overall ratio of fresh-vacancy pairs from $0%$ to $31.7%$ of the held-out gold.

*Rater protocol.* Each pair was rated independently by Claude Opus 4.7 — a different model tier and a different generation than the Sonnet 4.6 judge used in @sec:validation:ranking — on the anchor-only ordinal scale $\{0, 2, 4, 6, 8, 10\}$ with mandatory per-rating rationale, following Zheng et al. #cite(<zhengJudgingLLMasaJudge2023>). The rating protocol matches the Layer 5 protocol in every respect except the model tier and the dataset.

*Test-retest reliability.* A 30-pair stratified subsample of the held-out pairs was independently re-rated by the same Opus checkpoint with a rephrased rubric — the anchor descriptions were rewritten in alternative phrasings without changing the underlying ordinal semantics. The two passes yield Spearman $rho = 0.988$, exact-match agreement $89.7%$, within-$plus.minus 1$-anchor agreement $100%$, and mean absolute error $0.21$ on the native 0–10 scale. The test-retest correlation is publication-grade and bounds the upper limit of any correlation a system-under-test can achieve against this gold set: no scoring system can match a single-rater gold above the rater's own self-consistency.

*Production-system comparison.* For each pair I ran the production recruiter-side scoring service #raw("RecruiterMonolithicScoringService") at prompt version #raw("scoring_monolithic_recruiter_v1_6_source_weighting"). The full set of 398 predictions took $200$ seconds at concurrency four and cost approximately $\$1.00$ in Gemini 2.5 Flash invocations (2.4M input tokens, 109K output tokens). I record #raw("Score"), #raw("SubScores"), #raw("AntiFlagPenalty"), #raw("Confidence"), and the bilingual #raw("Reason") for each pair; the #raw("Score") field stores the raw linear composite (weighted sum of seven sub-scores multiplied by the anti-flag penalty), before #raw("ScoringCapService") applies any structural caps.

*Baselines.* Two classical-information-retrieval baselines were computed on the same 398 pairs without invoking any large language model: TF-IDF cosine over character-level word-boundary n-grams (range 3–5) of the concatenated curriculum-vitae and vacancy structured fields, with sub-linear term-frequency weighting and smoothed inverse-document frequency; and BM25 Okapi (k1=1.5, b=0.75) with per-curriculum-vitae min-max normalisation. Both baselines are implemented in pure .NET 8 inside the EvalTool project and require no external Python dependency.

*Cross-vendor configuration.* The system under test (Gemini 2.5 Flash, Google) and the rater (Claude Opus 4.7, Anthropic) come from different vendor families. The configuration mitigates — though does not eliminate — the same-vendor self-consensus risk named as a threat in @sec:validation:threats. The single-rater family limitation nevertheless remains and is named again in @sec:validation:heldout:limits.

=== Headline results <sec:validation:heldout:results>

Table 6.1 reports the overall metrics for the production scoring system on the 398-pair held-out gold. The full per-bin reliability diagram behind the Expected Calibration Error is in @tab:heldout:reliability.

#figure(
  table(
    columns: 3,
    align: (left, right, right),
    table.header[Metric][Value][95% CI],
    [Spearman $rho$], [$0.648$], [$[0.580, 0.712]$],
    [Kendall $tau$], [$0.524$], [—],
    [Quadratic Weighted Kappa], [$0.638$], [—],
    [Mean absolute error (0–10 scale)], [$1.638$], [$[1.533, 1.745]$],
    [$"NDCG"@3$ (per-curriculum-vitae avg)], [$0.813$], [—],
    [$"NDCG"@5$ (per-curriculum-vitae avg)], [$0.822$], [—],
    [Expected Calibration Error], [$0.138$], [—],
  ),
  caption: [Held-out evaluation overall metrics. $N = 398$. The confidence intervals are non-parametric 95-per-cent bootstrap intervals over 1000 resamples; the dataset was expanded in two stages (intra-pool 131 → 272, then fresh-vacancy 272 → 398) specifically to tighten these intervals and to populate the upper end of the score distribution.]
) <tab:heldout:overall>

*The lexical baseline is essentially tied on aggregate.* The TF-IDF cosine baseline achieves Spearman $rho = 0.666$ — within $0.02$ of the production Gemini system's $rho = 0.648$ — on the same 398 pairs. The BM25 baseline reaches $rho = 0.589$. Mean absolute error of the production system is $1.64$ versus TF-IDF $1.65$ and BM25 $1.43$. Taken at face value, the overall correlation numbers do not support the thesis claim that the language-model architecture improves match-quality scoring over a classical information-retrieval baseline.

*The aggregate hides a structural artefact.* Just under half of the held-out set ($189 / 398$) is the safety subset, where curricula vitae are professionally distant from the technology vacancies they are paired with. Catastrophic mismatch is trivial to detect from keyword absence; any scoring system that emits a low number when no keywords overlap will rank these pairs correctly, regardless of whether it understands the underlying match. Table 6.2 shows the per-subset breakdown.

#figure(
  table(
    columns: 5,
    align: (left, right, right, right, right),
    table.header[Subset][$n$][Gemini $rho$][Gemini QWK][Gemini MAE],
    [Overall], [$398$], [$0.648$], [$0.638$], [$1.64$],
    [Safety (catastrophic mismatch)], [$189$], [$0.514$], [$0.652$], [$1.66$],
    [Coverage + strong-fit], [$209$], [$0.694$], [$0.603$], [$1.62$],
    [Midrange (gold $in \{4, 6, 8, 10\}$)], [$110$], [*$0.738$*], [*$0.651$*], [*$1.13$*],
  ),
  caption: [Per-subset metrics for the Gemini scoring system on $N = 398$ pairs. The midrange filter — the regime where the recruiter's decision between candidates actually happens — is where the Gemini system performs best: Spearman $rho = 0.738$ and mean absolute error $1.13$ on a 0–10 scale (predictions on actionable pairs are off by approximately half an anchor step on average). Bold = best column on this subset.]
) <tab:heldout:subsets>

*The Gemini system retains a clear advantage on the recruiter workload.* On the midrange filter — the regime where the recruiter's decision between candidates actually happens — the Gemini system achieves Spearman $rho = 0.738$ ($+0.090$ over the aggregate) with mean absolute error $1.13$ on a 0–10 scale ($-0.51$ relative to the aggregate). On the coverage and strong-fit subset taken as a whole, Spearman is $0.694$. The lexical baseline appears competitive on the overall correlation only because the safety subset dominates the aggregate; on the regimes where the system is actually used, Gemini extends a clear advantage.

*The reading.* The Gemini scoring system is not a general upgrade over lexical baselines; it is a specific upgrade over lexical baselines on the recruiter workload, where catastrophic mismatches are already filtered out upstream by role-family selection and the remaining pairs are pairs the recruiter is genuinely choosing between. The honest framing — "the language-model architecture pays off where it is used" — is supportable from this evidence.

=== Calibration and the production-grade mitigation <sec:validation:heldout:calibration>

A scoring system used as a percentage must be calibrated, not just rank-correct: a predicted $65%$ that corresponds to a $50%$ true match-quality is misleading even if the ordering it produces is correct. The held-out evaluation includes the full ten-bin reliability diagram against the Opus gold and computes Expected Calibration Error.

#figure(
  table(
    columns: 5,
    align: (left, right, right, right, right),
    table.header[Predicted bin][$n$][Mean predicted][Mean gold][$|Delta|$],
    [$[0.0, 0.1)$], [$3$], [$0.058$], [$0.067$], [$0.009$],
    [$[0.1, 0.2)$], [$104$], [$0.162$], [$0.073$], [$0.089$],
    [$[0.2, 0.3)$], [$105$], [$0.255$], [$0.093$], [$0.162$],
    [$[0.3, 0.4)$], [$70$], [$0.340$], [$0.180$], [$0.160$],
    [$[0.4, 0.5)$], [$45$], [$0.442$], [$0.284$], [$0.157$],
    [$[0.5, 0.6)$], [$20$], [$0.532$], [$0.400$], [$0.132$],
    [$[0.6, 0.7)$], [$14$], [$0.645$], [$0.486$], [$0.159$],
    [$[0.7, 0.8)$], [$18$], [$0.743$], [$0.556$], [$0.187$],
    [$[0.8, 0.9)$], [$9$], [$0.845$], [$0.756$], [$0.089$],
    [$[0.9, 1.0]$], [$10$], [$0.934$], [$0.800$], [$0.134$],
  ),
  caption: [Reliability diagram for the raw production scoring on the 398-pair held-out gold. Nine of the ten populated bins show the predicted mean exceeding the gold mean; the lowest bin ($n = 3$) is essentially calibrated. The system is systematically over-confident across the mid- and upper distribution. Expected Calibration Error is $0.138$ before the post-hoc calibration described below.]
) <tab:heldout:reliability>

*The raw composite is systematically over-confident across the mid- and upper distribution.* Nine of the ten populated bins show the predicted mean exceeding the gold mean; only the lowest bin ($[0.0, 0.1)$, $n = 3$) is essentially calibrated (and slightly under-reports by $0.9$ percentage points). A pair the system reports as $25%$ in fact lands at $9%$; a pair reported as $53%$ in fact lands at $40%$; a pair reported as $74%$ lands at $56%$. The recruiter who reads the displayed percentages is reading inflated values by between nine and nineteen percentage points across the over-confident bins.

*Production-grade mitigation via post-hoc isotonic regression.* The over-confidence is corrected in production by a post-hoc isotonic-regression calibrator fitted offline on the held-out gold via the #raw("EvalTool fit-calibration") command. The fitter applies Pool-Adjacent-Violators isotonic regression and (independently) Platt scaling, evaluates both via 5-fold cross-validation on the same held-out, and persists the better of the two as a portable JSON artefact with the fitted knots. The chosen calibrator achieves $5$-fold cross-validated Expected Calibration Error of $0.027$ on this gold — an $80%$ relative reduction from the raw $0.138$. The artefact is loaded once at production startup by #raw("CalibratorLoader") and applied to every raw composite via #raw("IScoreCalibrator.Calibrate") before the recruiter UI displays the percentage. Runtime cost is one binary search over knots plus linear interpolation — sub-microsecond per call. *Calibration as a thesis-named limitation is therefore mitigated in production, not merely documented as future work.*

=== Caps on/off ablation <sec:validation:heldout:caps-ablation>

The production scoring pipeline applies #raw("ScoringCapService") after the language model emits the seven sub-scores; the service applies rule-based caps for seniority gap, experience gap, language gap, a combined experience+seniority cap, and a domain-alignment subtractor. The caps are an explicit architectural decision documented in @sec:design:scoring. The held-out evaluation provides the first controlled ablation of this decision: apply the caps offline to the recorded raw composite scores using each pair's recorded sub-scores and re-derived language-gap signal, then re-compute every metric.

#figure(
  table(
    columns: 4,
    align: (left, right, right, right),
    table.header[Metric][Caps OFF][Caps ON][$Delta$],
    [Spearman $rho$], [$0.648$], [$0.592$], [$-0.056$ ($-8.6%$)],
    [Kendall $tau$], [$0.524$], [$0.495$], [$-0.029$],
    [Quadratic Weighted Kappa], [$0.638$], [$0.632$], [$-0.006$ (essentially tied)],
    [Mean absolute error (0–10)], [$1.638$], [*$1.584$*], [$-0.054$ ($-3.3%$)],
    [$"NDCG"@3$], [$0.813$], [$0.806$], [$-0.007$ (preserved)],
    [$"NDCG"@5$], [$0.822$], [$0.799$], [$-0.023$ ($-2.8%$)],
    [Expected Calibration Error], [$0.138$], [*$0.118$*], [$-0.020$ ($-14.5%$)],
  ),
  caption: [Side-by-side metrics for the held-out evaluation with #raw("ScoringCapService") disabled (Caps OFF, raw language-model composite) and enabled (Caps ON, production behaviour). Caps fired on $304 / 398$ pairs ($76.4%$). Bold = better cell per metric. The caps substantially improve calibration ($-14.5%$ Expected Calibration Error, $-3.3%$ Mean Absolute Error) at essentially zero cost to top-of-list ranking ($"NDCG"@3$ moves by $0.007$, ordinal-rater agreement (QWK) moves by $0.006$). The pairwise rank correlation cost ($-0.056$ Spearman) is the trade-off the design accepts.]
) <tab:heldout:caps-ablation>

*The trade-off is interpretable.* Caps map distinct raw composite values onto identical capped values whenever the cap fires — a pair with raw composite $0.55$ and another with raw composite $0.62$ both land at $0.25$ if both trigger the combined experience+seniority cap. The mapping destroys pairwise rank information between similarly-bad pairs and Spearman drops accordingly. In return, the capped value is closer to the gold rating on average: pairs that scored $0.55$ raw when they should have been $0.20$ now show $0.25$, much closer to the gold. Mean absolute error drops by $3.3%$; Expected Calibration Error drops by $14.5%$; ordinal agreement (QWK) is preserved within noise; and top-of-list ranking (NDCG\@3) moves by $0.007$ — within the noise floor of the metric.

*The reading.* The #raw("ScoringCapService") is empirically a net positive on the metrics most relevant to the production use case. Calibration error — the most consequential failure mode when a recruiter reads a number on screen and treats it at face value — drops by $14.5%$. Top-of-list ranking is preserved. The cost is an $8.6%$ reduction in pairwise rank correlation, which the recruiter workflow does not directly expose. The architectural decision to apply caps is empirically justified on the held-out evidence; combined with the post-hoc isotonic calibrator in @sec:validation:heldout:calibration, total Expected Calibration Error in production is reduced from the raw $0.138$ to under $0.03$.

=== Limitations of the held-out evaluation <sec:validation:heldout:limits>

The held-out evaluation resolves several threats named in @sec:validation:threats but introduces or fails to retire others.

*Single-rater family.* All 398 ratings were produced by Claude Opus 4.7. The configuration is cross-vendor (the rater is Anthropic, the system under test is Google) and is therefore stronger than the intra-vendor configuration used in Layer 5, but it remains intra-family on the rater side. A multi-rater ensemble — adding an OpenAI GPT model and a Mistral or DeepSeek model as additional independent raters and reporting inter-rater Krippendorff's $alpha$ #cite(<krippendorffComputingKrippendorffsAlphareliability2011>) — would yield a published-grade inter-vendor methodology. The extension is recorded as future work in @sec:conclusion.

*Distribution skew of the safety subset.* Approximately half of the held-out set ($189 / 398 = 47.5%$) is in the safety subset where the gold rating is heavily concentrated at $0$ or $2$. The skew makes the aggregate metrics partly a measurement of how well the systems detect catastrophic mismatches, an arguably easier task than the recruiter's actual workload. The subset breakdown in @tab:heldout:subsets explicitly separates this regime.

*Prompt version ablation.* The pre-#raw("v1_6") prompt history was not preserved in version control; consequently the held-out evaluation reports the production prompt only and does not include a controlled #raw("v1_5") vs #raw("v1_6") comparison. The version-control gap is recorded as a process limitation in @sec:conclusion.

== Threats to validity <sec:validation:threats>

In this section I name the limitations of the evaluation and the specific extensions that would resolve each of them, in order from the most consequential to the least. Three threats named in earlier drafts of this chapter have been substantially mitigated by Layer 6 and are recorded here as retired or partially retired.

*Selection circularity (retired by Layer 6).* The Layer 3 score-error metric and the Layer 5 ranking gold both used the 391-pair set assembled alongside prompt iteration, leaving open the question of whether the reported numbers reflect prompt quality or convenient evaluation selection. The held-out evaluation in @sec:validation:heldout — 398 pairs the production prompt never saw, against ratings produced by a different Anthropic checkpoint than the Layer 5 judge — provides evidence on this question. The aggregate finding (Spearman $rho = 0.65$ against the Opus gold) and the subset breakdown (@tab:heldout:subsets) are both reported on a controlled-distribution held-out and do not share the selection-circularity threat.

*Vacancy-pool partial leakage (retired by Layer 6 Stage 2).* The Stage-1 held-out used pairs that were novel but drew vacancy text from the development pool, so the model had seen each vacancy during normalisation prompt iteration. The Stage-2 fresh-vacancy extension (@sec:validation:heldout:methodology) scraped and normalised 300 new vacancies after the production prompt was frozen and paired them with the 25-curriculum-vitae pool to produce 126 fresh-vacancy pairs. The production prompt provably did not see the vacancy text for these pairs during iteration. The threat is retired for $126 / 398 = 31.7%$ of the held-out gold.

*Calibration of the displayed percentage (mitigated in production).* The held-out reliability diagram (@tab:heldout:reliability) documents the production system's systematic over-confidence, Expected Calibration Error $0.138$. The mitigation in @sec:validation:heldout:calibration ships a post-hoc isotonic-regression calibrator that reduces 5-fold cross-validated Expected Calibration Error to $0.027$ — an $80%$ relative reduction — and is loaded at production startup by #raw("CalibratorLoader"). The recruiter UI now displays calibrated percentages whose magnitudes match the gold distribution. The threat moves from "identified, unmitigated" to "mitigated in production".

*Single-annotator gold sets (partially retired by Layer 6).* Layers 1 and 2 remain single-annotator. The held-out gold in @sec:validation:heldout uses a single LLM rater (Claude Opus 4.7) but reports test-retest reliability explicitly (Spearman $rho = 0.988$, exact-match $89.7%$, within-$plus.minus 1$-anchor $100%$). The publication-grade test-retest correlation bounds the upper limit of any system's correlation against this gold. A multi-rater inter-vendor extension remains future work and is recorded in @sec:conclusion.

*CV sample size.* The primary endpoint is computed over 14 CVs. The interval $[-0.168, +0.065]$ is wide enough that "directionally non-significant" — neither a clean win nor a clean loss — is the strongest thing the data support. A bigger gold set would either tighten the interval to exclude zero on one side or confirm the per-CV spread. I do not make per-family claims (Engineering, Data, Product, Design) at the inferential level, because no family has the 30+ CVs that a paired test would need; per-family numbers are descriptive only.

*Outlier influence on the headline delta.* The single broad-full-stack CV (#raw("17_realformat_swe_fullstack")) contributes $-0.643$ and drives most of the negative aggregate. Remove it and the mean drops to about $-0.001$. I keep the outlier in the headline because removing inconvenient data is itself a hazard, but I flag it openly here so the reader can decide how to weigh it.

*Composite Judge calibration defect.* The over-penalisation pattern documented in @sec:validation:score is the largest identifiable mechanism behind the observed negative cases on Layer 5. A hard $abs(s_"judge" - s_"linear") lt.eq 0.10$ clamp at the boundary of #raw("GeminiCompositeJudgeService") would isolate the Composite Judge's qualitative contribution from this artefact. The fix is documented and the post-hoc sensitivity check in @sec:validation:ranking quantifies its effect: applying the clamp arithmetically moves the mean delta from $Delta = -0.040$ to $Delta = +0.018$ and collapses the largest negative outlier from approximately $-0.54$ to essentially zero. Both pre- and post-clamp confidence intervals still cross zero, so the methodology's verdict of inconclusive at $alpha = 0.05$ is robust to whether the fix is deployed. Production deployment is recorded as future work in @sec:conclusion.

*Single-vendor judge family.* All judge ratings on Layers 4 and 5 originate within the Anthropic Claude family — Claude Opus 4.7 on Layer 4 and Claude Sonnet 4.6 on Layer 5. The intra-vendor configuration was a deliberate choice: it allowed a single rating pipeline and prompt format to be reused across the two layers, and the two model tiers match each layer's task. The inter-vendor extension — adding judges from at least one other vendor family, for example an OpenAI GPT model and a Mistral model — would strengthen the external validity of the Zheng et al. protocol and would let me measure inter-judge agreement directly. A Gemini Pro judge is not a suitable addition because Gemini Pro and the production Gemini 2.5 Flash share the same vendor family. I record the extension as future work in @sec:conclusion.

*Single-annotator gold sets in Layers 1, 2, and the spot-checks.* I curated the CV and vacancy gold normalisations as a single annotator. My author spot-checks of the Layer 4 and Layer 5 ratings are plausibility audits under a non-blind protocol rather than independent annotations, and I am not a disinterested rater. Inter-annotator agreement coefficients on a subset of the gold normalisations and on a subset of the match-quality ratings — by an annotator with no interest in the outcome — would be the appropriate extension; both are recorded as future work in @sec:conclusion.

*Judge-in-the-loop prompt iteration.* I used the Claude Opus 4.7 judge both while developing the Layer 4 prompts and for the final v6-versus-v4 comparison. The risk: v6 might just be better at pleasing one Anthropic checkpoint, not better at helping a human user. My defence is that the v6 prompt's gains come from hard structural changes — literal field interpolation, fixed sentence shapes, priority ordering — rather than from prose style. The per-dimension wins back this up: factual accuracy improved because the prompt forbids inference, specificity improved because of explicit #raw("vacancy_role_short") interpolation. A human comparison, or one judged by a different vendor, would confirm this and is recorded as future work.

*Surface-form sub-score calculators and production A/B.* The deterministic sub-score calculators use canonical-alias intersection and Jaccard overlap rather than embedding-based semantic similarity. A vacancy requiring Kubernetes and a CV listing Docker, Helm, and OpenShift score lower on the skill axis than the qualitative match would suggest. The Composite Judge is the design response — the model spots the equivalence — and what the Linear baseline misses is limited by surface-form matching. Separately, the v6 prompt is deployed to production; an A/B comparison against v4 under real-user click-through rates is recorded as the natural next step. The reason-quality evaluation is a strong predictor of user satisfaction in the cross-vendor judging literature, though it does not measure it directly.

*What would change the answer.* Three changes, in combination, would be sufficient to resolve the central thesis claim definitively. First, extending the CV gold set to at least thirty per role family would tighten the Layer 5 confidence interval enough to support per-family inference. Second, the Composite Judge calibration fix would remove the largest identifiable confound in the headline. Third, a multi-vendor judge ensemble would establish that the result is not an artefact of the single judge family chosen for the current evaluation. None of the three is conceptually difficult; all three are recorded as future work in @sec:conclusion.

*Held-out evaluation widens the picture but does not change the Layer 5 verdict.* Layer 6 adds an evaluation on 398 held-out pairs the production prompt never saw, with Spearman $rho = 0.65$ (95% CI $[0.58, 0.71]$) against a cross-vendor Claude Opus 4.7 gold, with $"NDCG"@5 = 0.82$ on top-of-list ranking, midrange-filter Spearman $rho = 0.738$ on the recruiter-workload regime, and a controlled ablation that empirically justifies the #raw("ScoringCapService") architectural decision. The held-out aggregate is consistent with the Layer 5 verdict and clarifies that the language-model architecture's advantage is conditional on the in-distribution recruiter workload.

== Chapter summary <sec:validation:summary>

In this chapter I described the layered evaluation methodology — the result of a mid-thesis pivot away from a structurally biased score-error endpoint — and the empirical findings it produced. Layers 1 and 2 are frozen at per-field scores of 0.896 (25 CVs) and 0.810 (355 of 357 vacancies). Layer 3 stays as a calibration diagnostic; the visible Linear-vs-Composite gap of 0.086 is explained by cap asymmetry, selection circularity, and a documented Composite Judge over-penalisation that has a one-line fix. Layer 4 shows a significant improvement of the v6 prompt over the v4 baseline on all four ordinal rubric dimensions (overall $Delta = +0.30$, 95 per cent CI $[+0.19, +0.40]$, $N approx 391$ pairs), judged by Claude Opus 4.7. Layer 5 — the primary endpoint of the earlier draft — is inconclusive on 14 CVs ($Delta$ NDCG\@10 $= -0.047$, CI $[-0.168, +0.065]$, judge Claude Sonnet 4.6); a post-hoc clamp shifts the headline to $+0.018$ without changing the verdict. Layer 6 — the held-out evaluation added late in the project — reports the production scoring system against a 398-pair held-out gold the prompt never saw, with Spearman $rho = 0.65$ (95% CI $[0.58, 0.71]$), $"NDCG"@5 = 0.82$, and midrange-filter Spearman $rho = 0.738$ on the recruiter-workload regime; the controlled #raw("ScoringCapService") ablation and the post-hoc isotonic calibrator (reducing Expected Calibration Error from $0.138$ to $0.027$ under 5-fold cross-validation, shipped to production) jointly justify the cap-and-calibrate architecture and retire the selection-circularity and vacancy-pool-leakage threats. The methodology stands regardless of the empirical verdict. The conditions under which the answer would tighten further are stated openly. Chapter 6 revisits the four objectives from the introduction and outlines the work that would close the remaining gaps.
