using Application.Common.Auditing;
using Application.Common.Authorization;
using MediatR;

namespace Application.Recruiter.Commands.CreateCandidateList;

public sealed record CreateCandidateListCommand(
    string Name,
    string? Description = null)
    : IRequest<CreateCandidateListResult>, IRequireRecruiterRole, IAuditableRequest
{
    // No IAuditableEntity: the ListId is generated by the handler and only
    // appears on the response. The default payload serializer captures Name +
    // Description, which is enough to answer "who created which list" via the
    // (UserId, Timestamp) index without joining on the result.
    public string AuditAction => "CreateCandidateList";
}

public sealed record CreateCandidateListResult(Guid ListId);
